config/routes.rb
Openhub::Application.routes.draw do
  resources :user_presentations

  resources :presentations

  get "openhub/index"

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  root to: "openhub#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :presentations


  def self.find_or_create_with_omniauth(auth)
    user = find_by_provider_and_uid(auth["provider"], auth["uid"]) 
    user || create_with_omniauth(auth)
  end

  private

  def self.create_with_omniauth(auth)
    create! do |user|
      user.uid      = auth["uid"]
      user.provider = auth["provider"]
      user.name     = auth["info"]["name"]
      user.twitter  = auth["info"]["nickname"]
      user.photo    = auth["info"]["image"]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/openhub_controller.rb
class OpenhubController < ApplicationController
  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_or_create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/openhub_helper.rb
module OpenhubHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title OpenHub
    = stylesheet_link_tag    :application
    = javascript_include_tag :application
    = csrf_meta_tags

  %body{style: "padding-top:60px"}
    %header
      .topbar
        .topbar-inner
          .container-fluid
            %h3
              = link_to "OpenHub", "/"
            .nav_right
              - if current_user
                %img{src: current_user.photo, height: "23px", width: "23px"}
                %span.name 
                  = current_user.name
                = link_to "Sign Out", signout_path
              - else
                = link_to "Sign it with Twitter", "/auth/twitter"

    %section
      .container-fluid
        = yield

app/views/openhub/index.html.erb
<h1>Openhub#index</h1>
<h2>added!</h2>
<p>Find me in app/views/openhub/index.html.erb</p>